# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 18:40
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_desc', models.CharField(max_length=500)),
                ('gift_from', models.CharField(max_length=200)),
                ('gift_notes', models.CharField(max_length=500)),
                ('save_date', models.DateTimeField(default=datetime.datetime.now)),
                ('edit_date', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
