# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 19:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifttrack', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='user',
        ),
        migrations.AlterField(
            model_name='gift',
            name='edit_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
