# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 11:09
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gifttrack', '0002_auto_20170414_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('save_date', models.DateTimeField(default=datetime.datetime.now)),
                ('edit_date', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GiftListFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('save_date', models.DateTimeField(default=datetime.datetime.now)),
                ('edit_date', models.DateTimeField(default=datetime.datetime.now)),
                ('gift_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gifttrack.GiftList')),
            ],
        ),
        migrations.AddField(
            model_name='gift',
            name='gift_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gifttrack.GiftList'),
            preserve_default=False,
        ),
    ]
