# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gifttrack', '0003_auto_20170503_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftlist',
            name='description',
            field=models.CharField(default='No Description', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='giftlist',
            name='edit_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='giftlist',
            name='save_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
