# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifttrack', '0004_auto_20170509_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftlist',
            name='description',
            field=models.CharField(default='No Description', max_length=500),
        ),
    ]
